python -u run_ca.py \
  --is_training 1 \
  --lradj 'TST' \
  --patience 3 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id Traffic \
  --model "$model_name" \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 1 \
  --d_model 128 \
  --d_ff 256 \
  --learning_rate 0.006 \
  --batch_size 24 \
  --fix_seed 2025 \
  --use_norm 1 \
  --wv "db1" \
  --m 3 \ 
  --enc_in 862 \
  --dec_in 862 \ 
  --c_out 862 \
  --des 'Exp' \ 
  --itr 3 \
  --alpha 0.6\
  --l1_weight 5e-5 \
